# Generated by Django 3.2 on 2021-04-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='test',
            new_name='text',
        ),
    ]
