# Generated by Django 3.2 on 2021-04-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_test_topic_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='test',
            new_name='text',
        ),
    ]
